# basic.yml
---
- hosts: all
  connection: local

  vars:
    dynamicpv_1: This Test Should Work.
    register: dynamicpvOutput_1

  vars_prompt:
    - name: dynamicpv_2
      prompt: "Enter a value"
      private: no
      register: dynamicpvOutput_2
  tasks:
   - debug: msg="{{ dynamicpv_1 }}. {{ dynamicpv_2 }} . Yes It Works!!!"
     ignore_errors: yes

   - debug: var=dynamicpv_1
     ignore_errors: yes

   - debug: var=dynamicpv_2
     ignore_errors: yes
